//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Droid_Game.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Droid_Game.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à HEADER;HEADER;2;3;4;5;6;7;8;9;10;1
        ///HARD;5;H;H;H;H;H;H;H;H;H;H
        ///HARD;6;H;H;H;H;H;H;H;H;H;H
        ///HARD;7;H;H;H;H;H;H;H;H;H;H
        ///HARD;8;H;H;H;H;H;H;H;H;H;H
        ///HARD;9;H;D;D;D;D;H;H;H;H;H
        ///HARD;10;D;D;D;D;D;D;D;D;H;H
        ///HARD;11;H;D;D;D;D;D;D;D;D;H
        ///HARD;12;H;H;S;S;S;H;H;H;H;H
        ///HARD;13;S;S;S;S;S;H;H;H;H;H
        ///HARD;14;S;S;S;S;S;H;H;H;H;H
        ///HARD;15;S;S;S;S;S;H;H;H;H;H
        ///HARD;16;S;S;S;S;S;H;H;H;H;H
        ///HARD;17;S;S;S;S;S;S;S;S;S;S
        ///HARD;18;S;S;S;S;S;S;S;S;S;S
        ///HARD;19;S;S;S;S;S;S;S;S;S;S
        ///HARD;20;S;S;S;S;S;S;S;S;S;S
        ///SOFT;2;H;H;H;D;D; [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string blackjack {
            get {
                return ResourceManager.GetString("blackjack", resourceCulture);
            }
        }
    }
}
